### ISSUE TITLE
unwanted scroll in admin view

### ISSUE THREAD

**Issue by samuelhackwill** [samuelhackwill/le-tiret-du-six#103]
as an admin, we don't want the window to scroll when we press the spacebar (admin spacebar)

in component spacebarcontrol.js
but maybe also admin.js

**Comment by moussor** [comment]
the problem is that the scroll happens before the keyup event therefore to prevent this from happening the scroll can be prevented by calling event.preventDefault() on keydown

**Comment by samuelhackwill** [comment]
this was fixed at some point. Thanks!
