### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by samuelhackwill** [samuelhackwill/le-tiret-du-six#39]
In the tracker module, the new method ( pull request #37 ) to display player's position in the text does not work if the admin scrolls in the text.

https://user-images.githubusercontent.com/6910260/137762744-a77d33dc-53ad-4967-990f-be0c3a6939f3.mov

**Comment by moussor** [comment]
I re implemented the new method that was in this commit https://github.com/samuelhackwill/le-tiret-du-six/commit/4becc48274140bd6aa620d6668aa101630587b1f and published it directly on master just cause we are foumalades.

**Comment by samuelhackwill** [comment]
on é dédiiingg
